<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="profile.aspx.cs" Inherits="SmartRecipeFinder.profile" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="profile-container">
        <!-- Left Sidebar (Profile) -->
        <div class="profile-sidebar">
            <img src="\images\user-login.png" alt="Profile Picture" class="profile-picture" /><br />
            <asp:Label ID="usernameLabel" runat="server" CssClass="username" Text="Username"></asp:Label>
            <asp:Label ID="emailLabel" runat="server" CssClass="user-email" Text="username@example.com"></asp:Label>
            &nbsp;<asp:Button ID="btnLogout" runat="server" CssClass="btn btn-logout" Text="Logout" OnClick="btnLogout_Click" />
            <asp:Button ID="btnDeleteAccount" runat="server" CssClass="btn btn-delete" Text="Delete Account" OnClick="btnDeleteAccount_Click" />
        </div>
        

        <!-- Right Section (User Info & Actions) -->
        <div class="profile-details">
            <h2>Account Information</h2>
            <p>
                <asp:Label ID="Label1" runat="server" Font-Bold="True" Text="Name: "></asp:Label>
                <asp:Label ID="displayNameLabel" runat="server" Text="What's in my Kitchen?"></asp:Label>
            </p>
            <p>
                <asp:Label ID="Label2" runat="server" Font-Bold="True" Text="Email: "></asp:Label>
                <asp:Label ID="displayEmailLabel" runat="server" Text="kitchen@example.com"></asp:Label>
            </p>
            <!-- Middle Section (Favorite Recipes) -->
            <h2>Favorite Recipes</h2>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" BackColor="White" BorderStyle="None" BorderWidth="1px" CellPadding="25" DataSourceID="SqlDataSource1" ForeColor="#6C584C" GridLines="Horizontal" CellSpacing="10" CssClass="gridview" PageSize="4" ShowHeader="False" Width="586px" DataKeyNames="Id">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" Visible="False" />
                    <asp:BoundField DataField="recipe-name" HeaderText="recipe-name" SortExpression="recipe-name" />
                    <asp:BoundField DataField="userId" HeaderText="userId" SortExpression="userId" Visible="False" />
                </Columns>
                <EditRowStyle BackColor="White" />
                <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#242121" />
            </asp:GridView>
            <br />
            <br />
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                SelectCommand="SELECT * FROM [favorite-recipe] WHERE [userId] = @userId ORDER BY [Id]" 
                DeleteCommand="DELETE FROM [favorite-recipe] WHERE [Id] = @Id AND [userId] = @userId">
                <SelectParameters>
                    <asp:SessionParameter Name="userId" SessionField="userId" Type="Int32" />
                </SelectParameters>

                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                    <asp:SessionParameter Name="userId" SessionField="userId" Type="Int32" />
                </DeleteParameters>
            </asp:SqlDataSource>

        </div>
    </div>
</asp:Content>
