<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="profile.aspx.cs" Inherits="SmartRecipeFinder.profile" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="profile-container">
        <!-- Left Sidebar (Profile) -->
        <div class="profile-sidebar">
            <img src="\images\user-login.png" alt="Profile Picture" class="profile-picture" /><br />
            <asp:Label ID="usernameLabel" runat="server" CssClass="username" Text="Username"></asp:Label>
            <asp:Label ID="emailLabel" runat="server" CssClass="user-email" Text="username@example.com"></asp:Label>
&nbsp;<asp:Button ID="btnLogout" runat="server" CssClass="btn btn-logout" Text="Logout" OnClick="btnLogout_Click" />
            <asp:Button ID="btnDeleteAccount" runat="server" CssClass="btn btn-delete" Text="Delete Account" OnClick="btnDeleteAccount_Click" />
        </div>
        

        <!-- Right Section (User Info & Actions) -->
        <div class="profile-details">
            <h2>Account Information</h2>
            <p>
                <asp:Label ID="Label1" runat="server" Font-Bold="True" Text="Name: "></asp:Label>
                <asp:Label ID="displayNameLabel" runat="server" Text="What's in my Kitchen?"></asp:Label>
            </p>
            <p>
                <asp:Label ID="Label2" runat="server" Font-Bold="True" Text="Email: "></asp:Label>
                <asp:Label ID="displayEmailLabel" runat="server" Text="kitchen@example.com"></asp:Label>
            </p>
            <!-- Middle Section (Favorite Recipes) -->
            <h2>Favorite Recipes</h2>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" BackColor="White" BorderStyle="None" BorderWidth="1px" CellPadding="25" DataSourceID="SqlDataSource1" ForeColor="#6C584C" GridLines="Horizontal" CellSpacing="10" CssClass="gridview" DataKeyNames="Id" PageSize="4" ShowHeader="False" Width="586px">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" Visible="False" />
                    <asp:BoundField DataField="recipe-name" HeaderText="recipe-name" SortExpression="recipe-name" />
                </Columns>
                <EditRowStyle BackColor="White" />
                <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#242121" />
            </asp:GridView>
            <br />
            <br />
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                SelectCommand="SELECT [Id], [recipe-name] FROM [recipe-details] WHERE [is-fav] = 1 ORDER BY [Id]" 
                DeleteCommand="UPDATE [recipe-details] SET [is-fav] = 0 WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" />
                </DeleteParameters>
            </asp:SqlDataSource>
        </div>
    </div>
</asp:Content>
